default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  username: <%= ENV["USER_NAME"] %>
  password: <%= ENV["PASSWORD"] %>
  database: demo_deploy_development
test:
  <<: *default
  database: demo_deploy_test
production:
  <<: *default
  database: demo_deploy_production
  username: demo_deploy
  password: 1
