default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["USER_NAME"] %>
  password: <%= ENV["PASSWORD"] %>
development:
  <<: *default
  database: demo_deploy_development
test:
  <<: *default
  database: demo_deploy_test
production:
  <<: *default
  database: demo_deploy_production
  username: demo_deploy
  password: <%= ENV['DEMO_DEPLOY_DATABASE_PASSWORD'] %>
